# Generated by Django 6.1 on 2026-08-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmsDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Language code from Django LANGUAGES (e.g. en, it).",
                        max_length=16,
                        verbose_name="Language",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agentweb_llms_documents",
                        to="sites.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLMS document",
                "verbose_name_plural": "LLMS documents",
                "ordering": ("site_id", "language"),
            },
        ),
        migrations.CreateModel(
            name="LlmsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(max_length=255, verbose_name="Heading"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Position"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="agentweb.llmsdocument",
                        verbose_name="LLMS document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="LlmsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Absolute URL or site-relative path (e.g. /rooms/).",
                        max_length=2048,
                        verbose_name="URL",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Notes"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Position"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="agentweb.llmssection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="llmsdocument",
            constraint=models.UniqueConstraint(
                fields=("site", "language"),
                name="agentweb_llmsdocument_site_language_uniq",
            ),
        ),
    ]
