# Generated by Django 6.1 on 2026-08-16 21:53

import agentweb.llms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentweb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmslink",
            name="url",
            field=models.CharField(
                help_text="Absolute http(s) URL or site-relative path (e.g. /rooms/).",
                max_length=2048,
                validators=[agentweb.llms.models.validate_llms_link_url],
                verbose_name="URL",
            ),
        ),
    ]
